[2023-11-25T03:55:09.546+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: outcomes_dag.load_dates_dim scheduled__2023-11-23T00:00:00+00:00 [queued]>
[2023-11-25T03:55:09.563+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: outcomes_dag.load_dates_dim scheduled__2023-11-23T00:00:00+00:00 [queued]>
[2023-11-25T03:55:09.566+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-11-25T03:55:09.578+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): load_dates_dim> on 2023-11-23 00:00:00+00:00
[2023-11-25T03:55:09.582+0000] {standard_task_runner.py:57} INFO - Started process 176 to run task
[2023-11-25T03:55:09.606+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'outcomes_dag', 'load_dates_dim', 'scheduled__2023-11-23T00:00:00+00:00', '--job-id', '22', '--raw', '--subdir', 'DAGS_FOLDER/outcomes_dag.py', '--cfg-path', '/tmp/tmpiap5q4rm']
[2023-11-25T03:55:09.611+0000] {standard_task_runner.py:85} INFO - Job 22: Subtask load_dates_dim
[2023-11-25T03:55:09.695+0000] {task_command.py:416} INFO - Running <TaskInstance: outcomes_dag.load_dates_dim scheduled__2023-11-23T00:00:00+00:00 [running]> on host 1ccd1734fa5f
[2023-11-25T03:55:09.799+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='outcomes_dag' AIRFLOW_CTX_TASK_ID='load_dates_dim' AIRFLOW_CTX_EXECUTION_DATE='2023-11-23T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-23T00:00:00+00:00'
[2023-11-25T03:55:12.760+0000] {logging_mixin.py:154} INFO - dim_dates loaded
[2023-11-25T03:55:12.763+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-11-25T03:55:12.809+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=outcomes_dag, task_id=load_dates_dim, execution_date=20231123T000000, start_date=20231125T035509, end_date=20231125T035512
[2023-11-25T03:55:12.931+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
